name: Firebase Deployment Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7

      - name: Set up Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        working-directory: terraform

  # Job for deploying to the staging environment during PRs
  staging-deploy:
    name: Staging Deployment for PR
    runs-on: ubuntu-latest
    needs: terraform-deploy  # Ensure Terraform runs first
    if: github.event_name == 'pull_request'  # Run only on PRs
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: car-tracker

      - name: Build Next.js App
        run: npm run build
        working-directory: car-tracker

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI (Staging)
        run: firebase use --add
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Hosting (Staging)
        run: firebase deploy --only hosting --project poc-car-delivery
        working-directory: car-tracker

  # Job for deploying to production when changes are pushed to main
  production-deploy:
    name: Production Deployment
    runs-on: ubuntu-latest
    needs: terraform-deploy  # Ensure Terraform runs first
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Run only on push to main
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: car-tracker

      - name: Build Next.js App
        run: npm run build
        working-directory: car-tracker

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI (Production)
        run: firebase use --add
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Hosting (Production)
        run: firebase deploy --only hosting --project poc-car-delivery
        working-directory: car-tracker
